accounts/urls.py
from django.urls import path

from .views import SignUpView


urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
]

forum/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from accounts import views as account_view
from board import views

urlpatterns = [
    path("home/", views.home, name="home"),
    # path("accounts/", include("accounts.urls")),  # new
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", account_view.SignUpView.as_view(), name='signup'),
    path("boards/<int:board_id>/topics/<int:topic_id>/posts/new/", views.add_post, name="add_post"),
    path("boards/<int:board_id>/topics/<int:topic_id>/posts/<int:post_id>/edit", views.edit_post, name="edit_post"),
    path("boards/<int:board_id>/topics/<int:topic_id>/", views.topic_posts, name="topic_posts"),
    path("boards/<int:board_id>/topics", views.board_topics, name="board_topics"),
    path("boards/<int:board_id>/new/", views.new_topic, name="new_topic"),
    path("create-board", views.create_board, name="create_board"),
    path("admin/", admin.site.urls),
]

accounts/models.py
from django.db import models

# Create your models here.

board/models.py
from django.db import models
from django.contrib.auth.models import User


class Board(models.Model):
    name = models.CharField(max_length=30, unique=True)
    description = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    def get_posts_count(self):
        return Post.objects.filter(topic__board=self).count()

    def get_last_post(self):
        return Post.objects.filter(topic__board=self).order_by('-created_at').first()

class Topic(models.Model):
    subject = models.CharField(max_length=255)
    last_updated = models.DateTimeField(auto_now_add=True)
    board = models.ForeignKey(
        Board, on_delete=models.CASCADE, related_name="topics"
    )
    starter = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="topics"
    )
    views = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.subject

class Post(models.Model):
    message = models.TextField(max_length=4000)
    topic = models.ForeignKey(
        Topic, on_delete=models.CASCADE, related_name="posts"
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(null=True)
    created_by = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="posts"
    )
    updated_by = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, related_name="+"
    )

    def __str__(self):
        return self.message

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional')
    email = forms.EmailField(max_length=254, help_text='Enter a valid email address')

    class Meta:
        model = User
        fields = [
            'username', 
            'first_name', 
            'last_name', 
            'email', 
            'password1', 
            'password2', 
            ]

board/forms.py
from django import forms
from .models import Topic, Post, Board

class NewTopicForm(forms.ModelForm):
    message = forms.CharField(widget=forms.Textarea(), max_length=4000)

    class Meta:
        model = Topic
        fields = ['subject', 'message']

class NewPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['message']

class EditPostForm(forms.ModelForm):
    message = forms.CharField(label="My Message", widget=forms.Textarea())
    class Meta:
        model = Post
        fields = ['message']

class CreateBoardForm(forms.ModelForm):
    class Meta:
        model = Board
        fields = ['name', 'description']

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic
from django import forms
from .forms import SignUpForm


class SignUpView(generic.CreateView):
    form_class = SignUpForm
    email = forms.EmailField(max_length=254, help_text='Enter a valid email address')
    success_url = reverse_lazy("home")
    template_name = "registration/signup.html"  
    

board/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Count
from .models import Board, Topic, Post
from .forms import NewTopicForm, NewPostForm, CreateBoardForm, EditPostForm
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.http import Http404

def home(request):
    boards = Board.objects.all()
    return render(request, "home.html", {"boards": boards})


def board_topics(request, board_id):
    board = get_object_or_404(Board, id=board_id)
    topics = board.topics.order_by('-last_updated').annotate(replies=Count('posts') - 1)
    return render(request, "topics.html", {"board": board, "topics": topics})

@login_required
def new_topic(request, board_id):
    board = get_object_or_404(Board, id=board_id)
    user = request.user
    if request.method == "POST":
        form = NewTopicForm(request.POST)
        if form.is_valid():
            topic = form.save()
            topic.board = board
            topic.starter = user
            topic.save()
            Post.objects.create(
                message=form.cleaned_data.get("message"),
                topic=topic,
                created_by=user,
            )
            return redirect("board_topics", board_id=board.id)
    else:
        form = NewTopicForm()

    return render(request, "new_topic.html", {"board": board, "form": form})


def topic_posts(request, board_id, topic_id):
    topic = get_object_or_404(Topic, board__id=board_id, id=topic_id)
    topic.views += 1
    topic.save()
    return render(request, "topic_posts.html", {"topic": topic})

@login_required
def add_post(request, board_id, topic_id):
    topic = get_object_or_404(Topic, id=topic_id)
    user = request.user

    if request.method == "POST":
        form = NewPostForm(request.POST)
        if form.is_valid():
            Post.objects.create(
                message=form.cleaned_data.get("message"),
                topic=topic,
                created_by=user,
            )
            return redirect("topic_posts", board_id=board_id, topic_id=topic_id)
    else:
        form = NewPostForm()

    return render(request, "add_post.html", {"topic": topic})

@login_required
def edit_post(request, board_id, topic_id, post_id):
    post = get_object_or_404(Post, id=post_id, created_by=request.user)
    topic = get_object_or_404(Topic, id=topic_id)
    form = EditPostForm(request.POST or None, instance=post)
    if form.is_valid():
        post.message = form.cleaned_data.get("message")
        post.updated_at = timezone.now()
        post.updated_by = request.user
        post.save()
        return redirect("topic_posts", board_id=board_id, topic_id=topic_id)
    return render(request, "edit_post.html", {"topic": topic, "form":form})

def create_board(request):
    if request.method == "POST":
        form = CreateBoardForm(request.POST)
        if form.is_valid():
            Board.objects.create(
                name=form.cleaned_data.get("name"),
                description=form.cleaned_data.get("description"),
            )
            return redirect("home")
    return render(request, "create_board.html")

templates/add_post.html
{% extends 'base.html' %}

{% block title %}Add new post{% endblock %}
{% block content %}
    <div class="px-4 py-4 sm:px-6 lg:px-8">
        <form class="space-y-8 divide-y divide-gray-200" method="post">
            {% csrf_token %}
            <div class="space-y-8 divide-y divide-gray-200 sm:space-y-5">
              <div class="space-y-6 sm:space-y-5">
                <div>
                  <h3 class="text-lg font-medium leading-6 text-gray-900">Adding new Post on Topic "{{ topic.subject }}"</h3>
                  <p class="mt-1 max-w-2xl text-sm text-gray-500"></p>
                </div>
          
                <div class="space-y-6 sm:space-y-5">
                  <div class="sm:grid sm:grid-cols-3 sm:items-start sm:gap-4 sm:border-t sm:border-gray-200 sm:pt-5">
                    <label for="about" class="block text-sm font-medium text-gray-700 sm:mt-px sm:pt-2">Message</label>
                    <div class="mt-1 sm:col-span-2 sm:mt-0">
                    <textarea id="message" name="message" rows="3" class="block w-full max-w-lg rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm" aria-invalid="true">{{message}}</textarea>
                      <p class="mt-2 text-sm text-gray-500">Write a message about your topic.</p>
                    </div>
                  </div>
        
                </div>
              </div>
            </div>
          
            <div class="pt-5">
              <div class="flex justify-center">
                <button type="submit" class="ml-3 inline-flex justify-center rounded-md border border-transparent bg-indigo-600 py-2 px-4 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2">Post</button>
              </div>
            </div>
          </form>
      </div>

  
{% endblock %}

templates/base.html
{% load tailwind_tags %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Django Boards{% endblock %}</title>
  {% tailwind_css %}
</head>
<body>
    {% block body %}
    <nav class="bg-gray-800">
        <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
          <div class="relative flex h-16 items-center justify-between">
            <div class="absolute inset-y-0 left-0 flex items-center sm:hidden">
              <!-- Mobile menu button-->
              <button type="button" class="inline-flex items-center justify-center rounded-md p-2 text-gray-400 hover:bg-gray-700 hover:text-white focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white" aria-controls="mobile-menu" aria-expanded="false">
                <!--
                  Icon when menu is closed.
      
                  Heroicon name: outline/bars-3
      
                  Menu open: "hidden", Menu closed: "block"
                -->
                <svg class="block h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
                </svg>
                <!--
                  Icon when menu is open.
      
                  Heroicon name: outline/x-mark
      
                  Menu open: "block", Menu closed: "hidden"
                -->
                <svg class="hidden h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>
            <div class="flex flex-1 items-center justify-center sm:items-stretch sm:justify-start">
              <div class="flex flex-shrink-0 items-center">
                <img class="block h-8 w-auto lg:hidden" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=500" alt="Your Company">
                <img class="hidden h-8 w-auto lg:block" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=500" alt="Your Company">
              </div>
              <div class="hidden sm:ml-6 sm:block">
                <div class="flex space-x-4">
                  <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
                  <a href="{% url 'home' %}" class="bg-gray-900 text-white px-3 py-2 rounded-md text-sm font-medium" aria-current="page">Boards</a>     
                  {%block topic%}
                  {%endblock%} 
                </div>
              </div>
            </div>
            {% block username %}
            
            {% endblock username%}
            {% if request.user.is_authenticated %}
            <a class="text-white" href="{% url "logout" %}">/ Logout</a>
            {% else %}
            <a class="text-white" href="{% url "login" %}">Login</a>
            {% endif %}
          </div>
        </div>
      
        <!-- Mobile menu, show/hide based on menu state. -->
        <div class="sm:hidden" id="mobile-menu">
          <div class="space-y-1 px-2 pt-2 pb-3">
            <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
            <a href="#" class="bg-gray-900 text-white block px-3 py-2 rounded-md text-base font-medium" aria-current="page">Boards</a>
      
            <a href="#" class="text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium">Team</a>
      
            <a href="#" class="text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium">Projects</a>
      
            <a href="#" class="text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium">Calendar</a>
          </div>
        </div>
      </nav>  
      <div>
        {% block content%}
        {% endblock %}
      </div>
      {% endblock body %}
</body>

</html>

templates/create_board.html
{% extends 'base.html' %}

{% block title %}Start a New Topic{% endblock %}
{% block content %}
<body>
    <div class="px-4 py-4 sm:px-6 lg:px-8">
        
        <form class="space-y-8 divide-y divide-gray-200" method="post">
            {% csrf_token %}
            <div class="space-y-8 divide-y divide-gray-200 sm:space-y-5">
              <div class="space-y-6 sm:space-y-5">
                <div>
                  <h3 class="text-lg font-medium leading-6 text-gray-900">Creating new  Board</h3>
                  <p class="mt-1 max-w-2xl text-sm text-gray-500"></p>
                </div>
          
                <div class="space-y-6 sm:space-y-5">
                  <div class="sm:grid sm:grid-cols-3 sm:items-start sm:gap-4 sm:border-t sm:border-gray-200 sm:pt-5">
                    <label for="name" class="block text-sm font-medium text-gray-700 sm:mt-px sm:pt-2">Name</label>
                    <div class="mt-1 sm:col-span-2 sm:mt-0">
                      <div class="flex max-w-lg rounded-md shadow-sm">
                        <input type="text" name="name" id="name" class="form-control block w-full min-w-0 flex-1 rounded-none rounded-r-md border-gray-300 focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm" aria-invalid="true">
                      </div>
                    </div>
                  </div>

                  <div class="sm:grid sm:grid-cols-3 sm:items-start sm:gap-4 sm:border-t sm:border-gray-200 sm:pt-5">
                    <label for="description" class="block text-sm font-medium text-gray-700 sm:mt-px sm:pt-2">Description</label>
                    <div class="mt-1 sm:col-span-2 sm:mt-0">
                      <div class="flex max-w-lg rounded-md shadow-sm">
                        <input type="text" name="description" id="description" class="form-control block w-full min-w-0 flex-1 rounded-none rounded-r-md border-gray-300 focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm" aria-invalid="true">
                      </div>
                    </div>
                  </div>
                  
                </div>
              </div>
            </div>
          
            <div class="pt-5">
              <div class="flex justify-center">
                <button type="submit" class="ml-3 inline-flex justify-center rounded-md border border-transparent bg-indigo-600 py-2 px-4 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2">Post</button>
              </div>
            </div>
          </form>
      </div>
</body>
  
{% endblock %}

templates/edit_post.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block title %}Add new post{% endblock %}
{% block content %}
    <div class="px-4 py-4 sm:px-6 lg:px-8">
        <form class="space-y-8 divide-y divide-gray-200" method="post">
            {% csrf_token %}
            <div class="space-y-8 divide-y divide-gray-200 sm:space-y-5">
              <div class="space-y-6 sm:space-y-5">
                <div>
                  <h3 class="text-lg font-medium leading-6 text-gray-900">Adding new Post on Topic "{{ topic.subject }}"</h3>
                  <p class="mt-1 max-w-2xl text-sm text-gray-500"></p>
                </div>
          
                <div class="space-y-6 sm:space-y-5">
                  <div class="sm:grid sm:grid-cols-3 sm:items-start sm:gap-4 sm:border-t sm:border-gray-200 sm:pt-5">
                    <label for="about" class="block text-sm font-medium text-gray-700 sm:mt-px sm:pt-2">{{ form.message.label }}</label>
                    <div class="mt-1 sm:col-span-2 sm:mt-0">
                      <!-- {{ form.message }} -->
                      {{  form.message|add_class:"w-full max-w-lg rounded-md " }}
                      <p class="mt-2 text-sm text-gray-500">Write a message about your topic.</p>
                    </div>
                  </div>
        
                </div>
              </div>
            </div>
          
            <div class="pt-5">
              <div class="flex justify-center">
                <button type="submit" class="ml-3 inline-flex justify-center rounded-md border border-transparent bg-indigo-600 py-2 px-4 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2">Post</button>
              </div>
            </div>
          </form>
      </div>

  
{% endblock %}

templates/home.html
{% extends "base.html"%}
{% block username %}
<a class="text-white" href="#">{{ user.username }}</a>
{% endblock username%}
{% block content%}
<body>
  <div class="px-4 py-4 sm:px-6 lg:px-8">
    <div class="sm:flex sm:items-center">
      <div class="sm:flex-auto">
        <h1 class="text-xl font-semibold text-gray-900">Boards</h1>
        <p class="mt-2 text-sm text-gray-700">A list all boards.</p>
      </div>
      <div class="mt-4 sm:mt-0 sm:ml-16 sm:flex-none">
        <button type="button"
          class="inline-flex items-center justify-center rounded-md border border-transparent bg-sky-500 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 sm:w-auto">
         <a href="{% url 'create_board' %}">Create board</a></button>
      </div>
    </div>
    <div class="mt-8 flex flex-col">
      <div class="-my-2 -mx-4 overflow-x-auto sm:-mx-6 lg:-mx-8">
        <div class="inline-block min-w-full py-2 align-middle md:px-6 lg:px-8">
          <div class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 md:rounded-lg">
            <table class="min-w-full divide-y divide-gray-300">
              <thead class="bg-gray-50">
                <tr>
                  <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">Board
                  </th>
                  <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Description</th>
                  <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Posts</th>
                  <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Topics</th>
                  <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Last Post</th>

                </tr>
              </thead>
              <tbody class="divide-y divide-gray-200 bg-white">
                {% for board in boards%}
                <tr class="odd:bg-white even:bg-slate-50 hover:bg-sky-300">
                  <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6">
                    <a href="{% url "board_topics" board.id %}">{{ board.name }}</a>
                  </td>
                  <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">{{ board.description }}</td>
                  <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">{{ board.get_posts_count }}</td>
                  <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">{{ board.topics.count }}</td>
                  <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                    {% if board.topics.count == 0%}
                      <div>No posts yet</div>
                    {% else %}
                      Created by {{ board.get_last_post.created_by}} at {{ board.get_last_post.created_at }}</td>
                    {%endif%}
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>
{% endblock %}

</html>

templates/new_topic.html
{% extends 'base.html' %}

{% block title %}Start a New Topic{% endblock %}
{% block topic %}
<a href="{% url 'board_topics' board.id %}" class="bg-gray-900 text-white px-3 py-2 rounded-md text-sm font-medium"
    aria-current="page">Topics</a>
{% endblock %}
{% block content %}
<body>
    <div class="px-4 py-4 sm:px-6 lg:px-8">
        
        <form class="space-y-8 divide-y divide-gray-200" method="post">
            {% csrf_token %}
            <div class="space-y-8 divide-y divide-gray-200 sm:space-y-5">
              <div class="space-y-6 sm:space-y-5">
                <div>
                  <h3 class="text-lg font-medium leading-6 text-gray-900">Creating new Topic on board "{{ board.name }}"</h3>
                  <p class="mt-1 max-w-2xl text-sm text-gray-500"></p>
                </div>
          
                <div class="space-y-6 sm:space-y-5">
                  <div class="sm:grid sm:grid-cols-3 sm:items-start sm:gap-4 sm:border-t sm:border-gray-200 sm:pt-5">
                    <label for="subject" class="block text-sm font-medium text-gray-700 sm:mt-px sm:pt-2">Subject</label>
                    <div class="mt-1 sm:col-span-2 sm:mt-0">
                      <div class="flex max-w-lg rounded-md shadow-sm">
                        <input type="text" name="subject" id="id_subject" class="form-control block w-full min-w-0 flex-1 rounded-none rounded-r-md border-gray-300 focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm" aria-invalid="true">
                      </div>
                    </div>
                  </div>
          
                  <div class="sm:grid sm:grid-cols-3 sm:items-start sm:gap-4 sm:border-t sm:border-gray-200 sm:pt-5">
                    <label for="about" class="block text-sm font-medium text-gray-700 sm:mt-px sm:pt-2">Message</label>
                    <div class="mt-1 sm:col-span-2 sm:mt-0">
                      <textarea id="message" name="message" rows="3" class="block w-full max-w-lg rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm" aria-invalid="true"></textarea>
                      <p class="mt-2 text-sm text-gray-500">Write a message about your topic.</p>
                    </div>
                  </div>
        
                </div>
              </div>
            </div>
          
            <div class="pt-5">
              <div class="flex justify-center">
                <button type="submit" class="ml-3 inline-flex justify-center rounded-md border border-transparent bg-indigo-600 py-2 px-4 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2">Post</button>
              </div>
            </div>
          </form>
      </div>
</body>
  
{% endblock %}

templates/topic_posts.html
{% extends 'base.html' %}

{% block title %}{{ topic.subject }}{% endblock %}

{% block content %}
<div class="px-4 py-4 sm:px-6 lg:px-8">
    <div class="sm:flex sm:items-center">
        <div class="sm:flex-auto">
            <h1 class="text-xl font-semibold text-gray-900">SUB: {{ topic.subject }}</h1>
            <p class="mt-2 text-sm text-gray-700"> Created by {{ topic.starter }}</p>
        </div>
        <div class="mt-4 sm:mt-0 sm:ml-16 sm:flex-none">
            <button type="button"
                class="inline-flex items-center justify-center rounded-md border border-transparent bg-sky-500 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 sm:w-auto">
                <a href="{% url 'add_post' topic.board.id topic.id %}">Add Post</a></button>
        </div>
    </div>
</div>
<div class="border-t border-gray-200 px-4 py-5 sm:p-0">
    <dl class="sm:divide-y sm:divide-gray-200">
        {% for post in topic.posts.all %}
        <div class="px-4 py-4 sm:px-6 lg:px-8 border-solid">
            <div class="sm:flex sm:items-center">
                <div class="sm:flex-auto">
                    <h1 class="text-m font-semibold text-gray-900">{{ post.created_by.username }} <span
                            style="color: grey; font-size: small;">posted at {{ post.created_at }}</span></h1>
                    <p class="mt-2 text-sm text-gray-700">{{ post.message }}</p>
                </div>
                {% if post.created_by == user %}

                <div class="mt-4 sm:mt-0 sm:ml-16 sm:flex-none">
                    <button type="button"
                        class="inline-flex items-center justify-center rounded-md border border-transparent bg-sky-500 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 sm:w-auto">
                        <a href="{% url 'edit_post' topic.board.id topic.id post.id %}">Edit</a> </button>
                </div>
                {% endif %}
            </div>
        </div>
        {% endfor %}
</div>
</div>
{% endblock %}

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>